2019-09-21 20:24:33.721 [error] <0.445.0>@Elixir.LarsonWeb.Rabbit:call:16 gen_server <0.445.0> terminated with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:33.776 [error] <0.445.0>@Elixir.LarsonWeb.Rabbit:call:16 CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:33.776 [error] <0.324.0>@Elixir.LarsonWeb.Rabbit:call:16 Supervisor {<0.324.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.445.0> exit with reason no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16 in context child_terminated
2019-09-21 20:24:37.847 [error] <0.452.0>@Elixir.LarsonWeb.Rabbit:call:16 gen_server <0.452.0> terminated with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:37.848 [error] <0.452.0>@Elixir.LarsonWeb.Rabbit:call:16 CRASH REPORT Process <0.452.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:37.848 [error] <0.318.0>@Elixir.LarsonWeb.Rabbit:call:16 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.452.0> exit with reason no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16 in context child_terminated
2019-09-21 21:53:54.631 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 21:53:54.638 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 21:53:54.638 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 21:53:57.414 [error] <0.560.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.560.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:57.444 [error] <0.560.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.560.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:57.444 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.560.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:53:58.451 [error] <0.565.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.565.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:58.452 [error] <0.565.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.565.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:58.452 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.565.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:00.456 [error] <0.566.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.566.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:00.458 [error] <0.566.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.566.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:00.458 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.566.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:08.978 [error] <0.436.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.436.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:08.992 [error] <0.436.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.436.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:08.992 [error] <0.322.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.322.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.436.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:10.071 [error] <0.443.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.443.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.072 [error] <0.443.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.072 [error] <0.323.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.443.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:10.362 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.456.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.362 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.362 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.456.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:55:06.509 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.437.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:06.509 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.437.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:06.510 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.437.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:55:07.266 [error] <0.444.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.444.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:07.267 [error] <0.444.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.444.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:07.267 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.444.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:01:14.890 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:01:14.902 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:01:14.903 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 22:05:09.442 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:05:09.453 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:05:09.454 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 22:05:11.894 [error] <0.718.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.718.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:11.903 [error] <0.718.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.718.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:11.904 [error] <0.324.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.324.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.718.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:12.922 [error] <0.724.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.724.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:12.923 [error] <0.724.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.724.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:12.924 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.724.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:14.927 [error] <0.725.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.725.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:14.928 [error] <0.725.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.725.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:14.929 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.725.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:19.932 [error] <0.726.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.726.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:19.935 [error] <0.726.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.726.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:19.936 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.726.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:29.939 [error] <0.728.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.728.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:29.939 [error] <0.728.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.728.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:29.939 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.728.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:41.860 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.437.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:41.861 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.437.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:41.862 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.437.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:42.858 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.456.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:42.860 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:42.861 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.456.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:43.989 [error] <0.462.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.462.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:43.991 [error] <0.462.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.462.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:43.991 [error] <0.323.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.462.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:45.995 [error] <0.463.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.463.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:45.996 [error] <0.463.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:45.997 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.463.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:50.623 [error] <0.479.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.479.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:50.624 [error] <0.479.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.479.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:50.624 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.479.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:51.636 [error] <0.485.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.485.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:51.637 [error] <0.485.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.485.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:51.637 [error] <0.320.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.320.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.485.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:53.639 [error] <0.486.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.486.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:53.641 [error] <0.486.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.486.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:53.641 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.486.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:58.644 [error] <0.487.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.487.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:58.645 [error] <0.487.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.487.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:58.645 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.487.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:08.647 [error] <0.488.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.488.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:08.649 [error] <0.488.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.488.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:08.649 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.488.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:18.652 [error] <0.489.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.489.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:18.653 [error] <0.489.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.489.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:18.653 [error] <0.323.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.489.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:28.655 [error] <0.490.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.490.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:28.655 [error] <0.490.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:28.656 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.490.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:38.954 [error] <0.510.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.510.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:38.955 [error] <0.510.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.510.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:38.955 [error] <0.320.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.320.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.510.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:40.011 [error] <0.515.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.515.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:40.012 [error] <0.515.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.515.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:40.013 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.515.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:42.015 [error] <0.516.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.516.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:42.016 [error] <0.516.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.516.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:42.017 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.516.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:47.020 [error] <0.517.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.517.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:47.021 [error] <0.517.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.517.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:47.022 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.517.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:08:51.982 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:08:51.984 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:08:51.984 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 22:12:44.059 [error] <0.624.0> ** Task <0.624.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:12:44.059 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:12:44.059 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.624.0> exit with reason watcher_command_error in context child_terminated
2019-10-16 23:08:18.522 [error] <0.735.0> gen_server <0.735.0> terminated with reason: socket_closed_unexpectedly
2019-10-16 23:08:18.523 [error] <0.749.0> gen_server <0.749.0> terminated with reason: socket_closed_unexpectedly
2019-10-16 23:08:18.523 [error] <0.719.0> gen_server <0.719.0> terminated with reason: socket_closed_unexpectedly
2019-10-16 23:08:18.527 [error] <0.749.0> CRASH REPORT Process <0.749.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-16 23:08:18.527 [error] <0.747.0> Supervisor {<0.747.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.748.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.749.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-16 23:08:18.527 [error] <0.735.0> CRASH REPORT Process <0.735.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-16 23:08:18.527 [error] <0.747.0> Supervisor {<0.747.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.748.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.749.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-16 23:08:18.527 [error] <0.733.0> Supervisor {<0.733.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.734.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.735.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-16 23:08:18.528 [error] <0.733.0> Supervisor {<0.733.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.734.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.735.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-16 23:08:18.528 [error] <0.719.0> CRASH REPORT Process <0.719.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-16 23:08:18.528 [error] <0.717.0> Supervisor {<0.717.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.718.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.719.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-16 23:09:08.718 [error] <0.482.0> gen_server <0.482.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:08.743 [error] <0.482.0> CRASH REPORT Process <0.482.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:08.743 [error] <0.330.0> Supervisor {<0.330.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.482.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:09:13.362 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:13.363 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:13.363 [error] <0.330.0> Supervisor {<0.330.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:09:17.277 [error] <0.489.0> gen_server <0.489.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:17.278 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:17.278 [error] <0.330.0> Supervisor {<0.330.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.489.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:09:20.431 [error] <0.490.0> gen_server <0.490.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:20.432 [error] <0.490.0> CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:09:20.432 [error] <0.329.0> Supervisor {<0.329.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.490.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:10:46.578 [error] <0.491.0> gen_server <0.491.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:10:46.579 [error] <0.491.0> CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:10:46.579 [error] <0.329.0> Supervisor {<0.329.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.491.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:10:47.586 [error] <0.492.0> gen_server <0.492.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:10:47.587 [error] <0.492.0> CRASH REPORT Process <0.492.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:10:47.587 [error] <0.328.0> Supervisor {<0.328.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.492.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:10:48.596 [error] <0.493.0> gen_server <0.493.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:10:48.597 [error] <0.493.0> CRASH REPORT Process <0.493.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-10-16 23:10:48.598 [error] <0.331.0> Supervisor {<0.331.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.493.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => <<"__">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-10-16 23:22:59.934 [error] <0.456.0>@Elixir.Jason:decode:55 gen_server <0.456.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:22:59.950 [error] <0.456.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:22:59.950 [error] <0.326.0>@Elixir.Jason:decode:55 Supervisor {<0.326.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.456.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-10-16 23:23:05.302 [error] <0.462.0>@Elixir.Jason:decode:55 gen_server <0.462.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:23:05.303 [error] <0.462.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.462.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:23:05.303 [error] <0.327.0>@Elixir.Jason:decode:55 Supervisor {<0.327.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.462.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-10-16 23:23:48.648 [error] <0.463.0>@Elixir.Jason:decode:55 gen_server <0.463.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:23:48.648 [error] <0.463.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:23:48.649 [error] <0.328.0>@Elixir.Jason:decode:55 Supervisor {<0.328.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.463.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-10-16 23:23:53.291 [error] <0.464.0>@Elixir.Jason:decode:55 gen_server <0.464.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:23:53.292 [error] <0.464.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.464.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55
2019-10-16 23:23:53.292 [error] <0.332.0>@Elixir.Jason:decode:55 Supervisor {<0.332.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.464.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => <<"__">>}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-10-17 13:52:45.939 [error] <0.692.0> gen_server <0.692.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.939 [error] <0.491.0> gen_server <0.491.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.940 [error] <0.615.0> gen_server <0.615.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.940 [error] <0.570.0> gen_server <0.570.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.940 [error] <0.508.0> gen_server <0.508.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.941 [error] <0.522.0> gen_server <0.522.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.941 [error] <0.692.0> CRASH REPORT Process <0.692.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-17 13:52:45.941 [error] <0.477.0> gen_server <0.477.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.943 [error] <0.536.0> gen_server <0.536.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.943 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-17 13:52:45.943 [error] <0.615.0> CRASH REPORT Process <0.615.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-17 13:52:45.943 [error] <0.508.0> CRASH REPORT Process <0.508.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-17 13:52:45.943 [error] <0.568.0> Supervisor {<0.568.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.569.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.570.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-17 13:52:45.943 [error] <0.690.0> Supervisor {<0.690.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.691.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.692.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-17 13:52:45.943 [error] <0.568.0> Supervisor {<0.568.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.569.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.570.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-17 13:52:45.944 [error] <0.690.0> Supervisor {<0.690.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.691.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.692.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-17 13:52:45.944 [error] <0.461.0> gen_server <0.461.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.944 [error] <0.613.0> Supervisor {<0.613.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.614.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.615.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-17 13:52:45.944 [error] <0.613.0> Supervisor {<0.613.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.614.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.615.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-17 13:52:45.944 [error] <0.506.0> Supervisor {<0.506.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.507.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.508.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-17 13:52:45.944 [error] <0.629.0> gen_server <0.629.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.944 [error] <0.506.0> Supervisor {<0.506.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.507.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[fun amqp_a..>,...],...}) at <0.508.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-17 13:52:45.944 [error] <0.678.0> gen_server <0.678.0> terminated with reason: socket_closed_unexpectedly
2019-10-17 13:52:45.944 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-17 13:52:45.945 [error] <0.491.0> CRASH REPORT Process <0.491.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-11-14 14:16:12.633 [error] <0.1992.0> gen_server <0.1992.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:12.636 [error] <0.1992.0> CRASH REPORT Process <0.1992.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:12.636 [error] <0.1841.0> Supervisor {<0.1841.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1992.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 14:16:49.952 [error] <0.1998.0> gen_server <0.1998.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:49.954 [error] <0.1998.0> CRASH REPORT Process <0.1998.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:49.954 [error] <0.1838.0> Supervisor {<0.1838.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1998.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 14:16:54.801 [error] <0.2000.0> gen_server <0.2000.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:54.803 [error] <0.2000.0> CRASH REPORT Process <0.2000.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:54.804 [error] <0.1841.0> Supervisor {<0.1841.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2000.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 14:16:58.049 [error] <0.2001.0> gen_server <0.2001.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:58.051 [error] <0.2001.0> CRASH REPORT Process <0.2001.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:16:58.051 [error] <0.1842.0> Supervisor {<0.1842.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2001.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 14:17:09.085 [error] <0.2002.0> gen_server <0.2002.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"Build">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:17:09.088 [error] <0.2002.0> CRASH REPORT Process <0.2002.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"Build">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 14:17:09.088 [error] <0.1843.0> Supervisor {<0.1843.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2002.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"Build">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 20:53:16.648 [error] <0.442.0> gen_server <0.442.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:53:16.657 [error] <0.442.0> CRASH REPORT Process <0.442.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:53:16.657 [error] <0.320.0> Supervisor {<0.320.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.442.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 20:56:28.242 [error] <0.460.0> gen_server <0.460.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:56:28.243 [error] <0.460.0> CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:56:28.243 [error] <0.324.0> Supervisor {<0.324.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.460.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 20:57:19.509 [error] <0.468.0> gen_server <0.468.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:57:19.510 [error] <0.468.0> CRASH REPORT Process <0.468.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:57:19.510 [error] <0.321.0> Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.468.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 20:57:24.645 [error] <0.470.0> gen_server <0.470.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:57:24.646 [error] <0.470.0> CRASH REPORT Process <0.470.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:57:24.646 [error] <0.317.0> Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.470.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 20:57:32.997 [error] <0.471.0> gen_server <0.471.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:57:32.998 [error] <0.471.0> CRASH REPORT Process <0.471.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 20:57:32.998 [error] <0.323.0> Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.471.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"cmd">> => <<"RunVNRTests">>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 21:00:57.159 [error] <0.478.0> gen_server <0.478.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 21:00:57.170 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 21:00:57.170 [error] <0.333.0> Supervisor {<0.333.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.478.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 21:01:54.301 [error] <0.465.0> gen_server <0.465.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 21:01:54.314 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-14 21:01:54.314 [error] <0.327.0> Supervisor {<0.327.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.465.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-14 21:31:18.071 [error] <0.485.0>@lists:reverse:147 CRASH REPORT Process <0.485.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-14 21:31:18.071 [error] <0.482.0>@lists:reverse:147 Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.63>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:40227 -> 127.0.0.1:5672">>,1}) at <0.485.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-14 21:31:18.071 [error] <0.482.0> Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.63>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:40227 -> 127.0.0.1:5672">>,1}) at <0.485.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-21 13:20:04.763 [error] <0.460.0>@lists:reverse:147 CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147
2019-11-21 13:20:04.763 [error] <0.457.0>@lists:reverse:147 Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:54751 -> 127.0.0.1:5672">>,1}) at <0.460.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147 in context child_terminated
2019-11-21 13:20:04.764 [error] <0.457.0> Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:54751 -> 127.0.0.1:5672">>,1}) at <0.460.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-21 13:26:04.932 [error] <0.460.0>@lists:reverse:147 CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147
2019-11-21 13:26:04.932 [error] <0.457.0>@lists:reverse:147 Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:39339 -> 127.0.0.1:5672">>,1}) at <0.460.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147 in context child_terminated
2019-11-21 13:26:04.932 [error] <0.457.0> Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:39339 -> 127.0.0.1:5672">>,1}) at <0.460.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-21 15:55:22.712 [error] <0.461.0>@lists:reverse:147 CRASH REPORT Process <0.461.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147
2019-11-21 15:55:22.712 [error] <0.458.0>@lists:reverse:147 Supervisor {<0.458.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.14>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.460.0>, {<<"client 127.0.0.1:41633 -> 127.0.0.1:5672">>,1}) at <0.461.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147 in context child_terminated
2019-11-21 15:55:22.712 [error] <0.458.0> Supervisor {<0.458.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.14>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.460.0>, {<<"client 127.0.0.1:41633 -> 127.0.0.1:5672">>,1}) at <0.461.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-21 16:02:20.321 [error] <0.496.0>@lists:reverse:147 CRASH REPORT Process <0.496.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147
2019-11-21 16:02:20.321 [error] <0.493.0>@lists:reverse:147 Supervisor {<0.493.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.495.0>, {<<"client 127.0.0.1:35099 -> 127.0.0.1:5672">>,1}) at <0.496.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147 in context child_terminated
2019-11-21 16:02:20.321 [error] <0.493.0> Supervisor {<0.493.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.495.0>, {<<"client 127.0.0.1:35099 -> 127.0.0.1:5672">>,1}) at <0.496.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-21 16:02:55.277 [error] <0.466.0>@lists:reverse:147 CRASH REPORT Process <0.466.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-21 16:02:55.277 [error] <0.463.0>@lists:reverse:147 Supervisor {<0.463.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.465.0>, {<<"client 127.0.0.1:33171 -> 127.0.0.1:5672">>,1}) at <0.466.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-21 16:02:55.277 [error] <0.463.0> Supervisor {<0.463.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.465.0>, {<<"client 127.0.0.1:33171 -> 127.0.0.1:5672">>,1}) at <0.466.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:06:09.471 [error] <0.460.0>@lists:reverse:147 CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147
2019-11-28 14:06:09.471 [error] <0.457.0>@lists:reverse:147 Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:52601 -> 127.0.0.1:5672">>,1}) at <0.460.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<"BuildDebug">>,<<"fsx">> => <<"build.fsx">>,<<"para...">> => ...}}) line 147 in context child_terminated
2019-11-28 14:06:09.471 [error] <0.457.0> Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.13>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:52601 -> 127.0.0.1:5672">>,1}) at <0.460.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:17:36.344 [error] <0.457.0>@Elixir.Jason:decode:55 gen_server <0.457.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:17:36.394 [error] <0.457.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:17:36.394 [error] <0.331.0>@Elixir.Jason:decode:55 Supervisor {<0.331.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.457.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-11-28 14:18:18.181 [error] <0.463.0>@Elixir.Jason:decode:55 gen_server <0.463.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:18:18.183 [error] <0.463.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:18:18.183 [error] <0.327.0>@Elixir.Jason:decode:55 Supervisor {<0.327.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.463.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-11-28 14:18:22.176 [error] <0.464.0>@Elixir.Jason:decode:55 gen_server <0.464.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:18:22.177 [error] <0.464.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.464.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:18:22.177 [error] <0.331.0>@Elixir.Jason:decode:55 Supervisor {<0.331.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.464.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-11-28 14:18:23.179 [error] <0.465.0>@Elixir.Jason:decode:55 gen_server <0.465.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:18:23.180 [error] <0.465.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:18:23.181 [error] <0.331.0>@Elixir.Jason:decode:55 Supervisor {<0.331.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.465.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-11-28 14:20:32.663 [error] <0.465.0>@Elixir.Jason:decode:55 gen_server <0.465.0> terminated with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:20:32.674 [error] <0.465.0>@Elixir.Jason:decode:55 CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55
2019-11-28 14:20:32.675 [error] <0.327.0>@Elixir.Jason:decode:55 Supervisor {<0.327.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.465.0> exit with reason bad argument in call to erlang:iolist_to_binary(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) in 'Elixir.Jason':decode/2 line 55 in context child_terminated
2019-11-28 14:21:15.736 [error] <0.503.0>@lists:reverse:147 CRASH REPORT Process <0.503.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:21:15.737 [error] <0.500.0>@lists:reverse:147 Supervisor {<0.500.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.68>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.502.0>, {<<"client 127.0.0.1:54065 -> 127.0.0.1:5672">>,1}) at <0.503.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:21:15.737 [error] <0.500.0> Supervisor {<0.500.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.68>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.502.0>, {<<"client 127.0.0.1:54065 -> 127.0.0.1:5672">>,1}) at <0.503.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:22:11.887 [error] <0.465.0> gen_server <0.465.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-28 14:22:11.898 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-28 14:22:11.898 [error] <0.330.0> Supervisor {<0.330.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.465.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-28 14:29:07.232 [error] <0.458.0>@Elixir.LarsonWeb.ScoreChannel:handle_in:18 gen_server <0.458.0> terminated with reason: no match of right hand value <<"{\"cmd\":\"build\",\"fsx\":\"build.fsx\",\"params\":\" \"}">> in 'Elixir.LarsonWeb.ScoreChannel':handle_in/3 line 18
2019-11-28 14:29:07.246 [error] <0.458.0>@Elixir.LarsonWeb.ScoreChannel:handle_in:18 CRASH REPORT Process <0.458.0> with 0 neighbours crashed with reason: no match of right hand value <<"{\"cmd\":\"build\",\"fsx\":\"build.fsx\",\"params\":\" \"}">> in 'Elixir.LarsonWeb.ScoreChannel':handle_in/3 line 18
2019-11-28 14:29:07.246 [error] <0.333.0>@Elixir.LarsonWeb.ScoreChannel:handle_in:18 Supervisor {<0.333.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.458.0> exit with reason no match of right hand value <<"{\"cmd\":\"build\",\"fsx\":\"build.fsx\",\"params\":\" \"}">> in 'Elixir.LarsonWeb.ScoreChannel':handle_in/3 line 18 in context child_terminated
2019-11-28 14:29:58.954 [error] <0.455.0>@Elixir.LarsonWeb.ScoreChannel:handle_in:18 gen_server <0.455.0> terminated with reason: no match of right hand value <<"{\"cmd\":\"build\",\"fsx\":\"build.fsx\",\"params\":\" \"}">> in 'Elixir.LarsonWeb.ScoreChannel':handle_in/3 line 18
2019-11-28 14:29:58.972 [error] <0.455.0>@Elixir.LarsonWeb.ScoreChannel:handle_in:18 CRASH REPORT Process <0.455.0> with 0 neighbours crashed with reason: no match of right hand value <<"{\"cmd\":\"build\",\"fsx\":\"build.fsx\",\"params\":\" \"}">> in 'Elixir.LarsonWeb.ScoreChannel':handle_in/3 line 18
2019-11-28 14:29:58.972 [error] <0.320.0>@Elixir.LarsonWeb.ScoreChannel:handle_in:18 Supervisor {<0.320.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.455.0> exit with reason no match of right hand value <<"{\"cmd\":\"build\",\"fsx\":\"build.fsx\",\"params\":\" \"}">> in 'Elixir.LarsonWeb.ScoreChannel':handle_in/3 line 18 in context child_terminated
2019-11-28 14:30:43.707 [error] <0.485.0>@lists:reverse:147 CRASH REPORT Process <0.485.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:30:43.707 [error] <0.482.0>@lists:reverse:147 Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.64>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:55245 -> 127.0.0.1:5672">>,1}) at <0.485.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:30:43.707 [error] <0.482.0> Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.64>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:55245 -> 127.0.0.1:5672">>,1}) at <0.485.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:33:17.443 [error] <0.470.0>@lists:reverse:147 CRASH REPORT Process <0.470.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:33:17.443 [error] <0.467.0>@lists:reverse:147 Supervisor {<0.467.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.469.0>, {<<"client 127.0.0.1:48001 -> 127.0.0.1:5672">>,1}) at <0.470.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:33:17.443 [error] <0.467.0> Supervisor {<0.467.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.469.0>, {<<"client 127.0.0.1:48001 -> 127.0.0.1:5672">>,1}) at <0.470.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:36:08.454 [error] <0.502.0>@lists:reverse:147 CRASH REPORT Process <0.502.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:36:08.455 [error] <0.499.0>@lists:reverse:147 Supervisor {<0.499.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.21>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.501.0>, {<<"client 127.0.0.1:49029 -> 127.0.0.1:5672">>,1}) at <0.502.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:36:08.455 [error] <0.499.0> Supervisor {<0.499.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.21>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.501.0>, {<<"client 127.0.0.1:49029 -> 127.0.0.1:5672">>,1}) at <0.502.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:37:28.441 [error] <0.481.0>@lists:reverse:147 CRASH REPORT Process <0.481.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:37:28.441 [error] <0.478.0>@lists:reverse:147 Supervisor {<0.478.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.63>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.480.0>, {<<"client 127.0.0.1:53555 -> 127.0.0.1:5672">>,1}) at <0.481.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:37:28.441 [error] <0.478.0> Supervisor {<0.478.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.63>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.480.0>, {<<"client 127.0.0.1:53555 -> 127.0.0.1:5672">>,1}) at <0.481.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:38:48.686 [error] <0.513.0>@lists:reverse:147 CRASH REPORT Process <0.513.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:38:48.686 [error] <0.510.0>@lists:reverse:147 Supervisor {<0.510.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.69>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.512.0>, {<<"client 127.0.0.1:44813 -> 127.0.0.1:5672">>,1}) at <0.513.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:38:48.687 [error] <0.510.0> Supervisor {<0.510.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.69>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.512.0>, {<<"client 127.0.0.1:44813 -> 127.0.0.1:5672">>,1}) at <0.513.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:46:34.318 [error] <0.486.0>@lists:reverse:147 CRASH REPORT Process <0.486.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:46:34.318 [error] <0.483.0>@lists:reverse:147 Supervisor {<0.483.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.65>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.485.0>, {<<"client 127.0.0.1:55495 -> 127.0.0.1:5672">>,1}) at <0.486.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:46:34.318 [error] <0.483.0> Supervisor {<0.483.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.65>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.485.0>, {<<"client 127.0.0.1:55495 -> 127.0.0.1:5672">>,1}) at <0.486.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:48:26.281 [error] <0.519.0>@lists:reverse:147 CRASH REPORT Process <0.519.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:48:26.282 [error] <0.516.0>@lists:reverse:147 Supervisor {<0.516.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.71>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.518.0>, {<<"client 127.0.0.1:41963 -> 127.0.0.1:5672">>,1}) at <0.519.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:48:26.282 [error] <0.516.0> Supervisor {<0.516.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.71>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.518.0>, {<<"client 127.0.0.1:41963 -> 127.0.0.1:5672">>,1}) at <0.519.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:49:34.454 [error] <0.468.0>@lists:reverse:147 CRASH REPORT Process <0.468.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:49:34.454 [error] <0.465.0>@lists:reverse:147 Supervisor {<0.465.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.467.0>, {<<"client 127.0.0.1:54853 -> 127.0.0.1:5672">>,1}) at <0.468.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:49:34.454 [error] <0.465.0> Supervisor {<0.465.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.467.0>, {<<"client 127.0.0.1:54853 -> 127.0.0.1:5672">>,1}) at <0.468.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:49:45.116 [error] <0.500.0>@lists:reverse:147 CRASH REPORT Process <0.500.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:49:45.117 [error] <0.497.0>@lists:reverse:147 Supervisor {<0.497.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.21>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.499.0>, {<<"client 127.0.0.1:43617 -> 127.0.0.1:5672">>,1}) at <0.500.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:49:45.117 [error] <0.497.0> Supervisor {<0.497.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.21>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.499.0>, {<<"client 127.0.0.1:43617 -> 127.0.0.1:5672">>,1}) at <0.500.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-28 14:50:28.735 [error] <0.532.0>@lists:reverse:147 CRASH REPORT Process <0.532.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-11-28 14:50:28.735 [error] <0.529.0>@lists:reverse:147 Supervisor {<0.529.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.27>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.531.0>, {<<"client 127.0.0.1:37907 -> 127.0.0.1:5672">>,1}) at <0.532.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-11-28 14:50:28.735 [error] <0.529.0> Supervisor {<0.529.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.27>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.531.0>, {<<"client 127.0.0.1:37907 -> 127.0.0.1:5672">>,1}) at <0.532.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 22:33:10.739 [error] <0.480.0>@lists:reverse:147 CRASH REPORT Process <0.480.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-12-04 22:33:10.739 [error] <0.477.0>@lists:reverse:147 Supervisor {<0.477.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.479.0>, {<<"client 127.0.0.1:44517 -> 127.0.0.1:5672">>,1}) at <0.480.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-12-04 22:33:10.739 [error] <0.477.0> Supervisor {<0.477.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.479.0>, {<<"client 127.0.0.1:44517 -> 127.0.0.1:5672">>,1}) at <0.480.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 22:34:38.218 [error] <0.479.0>@lists:reverse:147 CRASH REPORT Process <0.479.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-12-04 22:34:38.218 [error] <0.476.0>@lists:reverse:147 Supervisor {<0.476.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.478.0>, {<<"client 127.0.0.1:50721 -> 127.0.0.1:5672">>,1}) at <0.479.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-12-04 22:34:38.218 [error] <0.476.0> Supervisor {<0.476.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.478.0>, {<<"client 127.0.0.1:50721 -> 127.0.0.1:5672">>,1}) at <0.479.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 22:45:31.120 [error] <0.486.0>@lists:reverse:147 CRASH REPORT Process <0.486.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-12-04 22:45:31.120 [error] <0.483.0>@lists:reverse:147 Supervisor {<0.483.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.485.0>, {<<"client 127.0.0.1:42409 -> 127.0.0.1:5672">>,1}) at <0.486.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-12-04 22:45:31.120 [error] <0.483.0> Supervisor {<0.483.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.485.0>, {<<"client 127.0.0.1:42409 -> 127.0.0.1:5672">>,1}) at <0.486.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 22:47:19.602 [error] <0.480.0>@lists:reverse:147 CRASH REPORT Process <0.480.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147
2019-12-04 22:47:19.602 [error] <0.477.0>@lists:reverse:147 Supervisor {<0.477.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.479.0>, {<<"client 127.0.0.1:47207 -> 127.0.0.1:5672">>,1}) at <0.480.0> exit with reason no function clause matching lists:reverse(#{<<"player_score">> => #{<<"cmd">> => <<>>,<<"fsx">> => <<"build.fsx">>,<<"params">> => <<>>}}) line 147 in context child_terminated
2019-12-04 22:47:19.602 [error] <0.477.0> Supervisor {<0.477.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.61>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.479.0>, {<<"client 127.0.0.1:47207 -> 127.0.0.1:5672">>,1}) at <0.480.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 22:53:58.948 [error] <0.462.0> gen_server <0.462.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"score:platformer\"\n  event: \"broadcast_score\"\n  payload: :ok\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 200
2019-12-04 22:53:58.967 [error] <0.462.0> CRASH REPORT Process <0.462.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"score:platformer\"\n  event: \"broadcast_score\"\n  payload: :ok\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 200
2019-12-04 22:53:58.967 [error] <0.334.0> Supervisor {<0.334.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.462.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"score:platformer\"\n  event: \"broadcast_score\"\n  payload: :ok\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 200 in context child_terminated
2019-12-04 22:54:01.289 [error] <0.483.0> gen_server <0.483.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"score:platformer\"\n  event: \"broadcast_score\"\n  payload: :ok\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 200
2019-12-04 22:54:01.290 [error] <0.483.0> CRASH REPORT Process <0.483.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"score:platformer\"\n  event: \"broadcast_score\"\n  payload: :ok\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 200
2019-12-04 22:54:01.290 [error] <0.338.0> Supervisor {<0.338.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.483.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"topic and event must be strings, message must be a map, got:\n\n  topic: \"score:platformer\"\n  event: \"broadcast_score\"\n  payload: :ok\n\n">>} in 'Elixir.Phoenix.Channel.Server':raise_invalid_message/3 line 200 in context child_terminated
